# Generated by Django 3.1.7 on 2021-03-06 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20210306_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
