# Generated by Django 3.1.7 on 2021-03-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_remove_flight_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.IntegerField(default='1'),
        ),
    ]
